### ISSUE TITLE
Changing units for a python measurement

### ISSUE THREAD

**Issue by dlerohl** [Reveal-Energy-Services/orchid-python-api#10]
orchid.net_quantity has many functions for converting between .NET and python objects. For the .NET objects it has the functionality to change the units for a measurement but does not have the ability for python measurements. 

When comparing results from 2 .ifrac files (1 in UsOilField and 1 in Metric). The screenshot shows my code for converting the bbl to m3 units. It would be nice to have a orchid.net_quantity.as_measurement_in_unit(measurement, to_unit) function.

![image](https://user-images.githubusercontent.com/13491198/99445203-e97dfc80-28e2-11eb-9d01-6c6ab01a7871.png)

**Comment by mrwizard82d1** [comment]
We need to implement this function.
