### ISSUE TITLE
Orchid Example Folder

### ISSUE THREAD

**Issue by dlerohl** [Reveal-Energy-Services/orchid-python-api#2]
After installing using pip, the example folder is in the /env/site-packages and not in the orchid folder. 

It would be helpful to have everything needed in the orchid folder.

**Comment by mrwizard82d1** [comment]
This is a problem. Unfortunately, when I encountered this issue in my own testing, I wrote a script to copy the files in the `examples` directory from the virtual environment `site-packages` directory to my test directory. When I activated the virtual environment for that directory, I was able to view and execute these examples.

Although I may be able to put these files in the `scripts` directory of the virtual environment (which is added to the executable path of the current user), unless I added a "she-bang" line to the notebook (I think that would work, but I'm not highly confident), or the user associated the notebook files (`.ipynb') with IPython or Jupyter, I do not believe they would automatically run in the virtual environment. 

I do not believe that the PyPI download process has a "hook" to install this files in any directory outside the `site-packages` directory, but I've not really tried to find such a "hook."

I suspect the best solution is to create another repository for the orchid examples. We *would not* generate a PyPI package for this directory, but would rely on the user, perhaps with instructions describing how, downloading the source code for these examples into a directory associated with a virtual environment.

**Comment by mrwizard82d1** [comment]
Addressed this in the latest (2020.4.191) release. This release now contains two commands:

- `copy_orchid_examples`
- `use_orchid_test_data`

The command, `copy_orchid_examples`, copies the orchid examples from the currently activated virtual environment into a directory (default: the current directory). The command, `use_orchid_test_data`, changes the path names of test data files to directory specified by the user.
