### ISSUE TITLE
Documentation with User Address

### ISSUE THREAD

**Issue by dlerohl** [Reveal-Energy-Services/orchid-python-api#4]
![image](https://user-images.githubusercontent.com/13491198/90688486-2844dd80-e234-11ea-9b44-c02a9a02a8c5.png)

This reference usually shows /path/to/usr/ but has your actual user path in the documentation. Wanted to raise this to your attention.

**Comment by mrwizard82d1** [comment]
We need to review the documentation. The fix may be as simply as describing the use of `C:/Users/larry.jones` as a concrete example instead of a command to be copied.

**Comment by mrwizard82d1** [comment]
Repaired in release 2020.4.232.
