### ISSUE TITLE
Create a central place to update test data locations

### ISSUE THREAD

**Issue by matthewtrahan** [Reveal-Energy-Services/orchid-python-api#7]
From PR review:

Matthew:
Maybe we could have some script or maybe even a settings file where we can set the path to the test data. We have the path\to and this in a few places now so it might make it easier.

Larry:
It's been awhile thinking about this problem, but it is good to think about this again.

We already have a python.yaml configuration file. I'd thought about putting test data locations in this file. Perhaps its time to revisit this idea (since a user should know where they have "installed" the integration test data - as opposed to the install location of Orchid itself: the other configuration option.

**Comment by mrwizard82d1** [comment]
Thanks, Matthew, for the issue.

I do like this idea. My script to make the examples work with a user's specific location for Orchid test data works, at least in my tests, but it does seem simpler if we could configure the issue.

Additionally, I believe Sean advocated for using environment variables. Although Windows users might be less familiar with this technique, it, too, is well-established and allows both flexibility and "overriding". (Often, Unix applications look for an option from the command line, from a configuration file, from an environment variable, and finally a default value. (I may have mixed up the typical "order" of the middle two items.))

**Comment by mrwizard82d1** [comment]
Repaired and released with version 2020.4.361
