### ISSUE TITLE
Kiwisolver dependency Error

### ISSUE THREAD

**Issue by dlerohl** [Reveal-Energy-Services/orchid-python-api#9]
When creating the virtual environment using 'poetry install', I got an error when installing kiwisolver. 
In the poetry.lock file, it specifies the version to be 1.3.0 which has been yanked and replaced with 1.3.1 on the version history.

**Comment by dlerohl** [comment]
Running 'poetry update' solves the dependency and install kiwisolver 1.3.1

**Comment by mrwizard82d1** [comment]
Running `poetry update` is the workaround for this issue. It should be repaired with the next release.

**Comment by mrwizard82d1** [comment]
Repaired with release 2020.4.595.

**Comment by mrwizard82d1** [comment]
Forgot to close issue.
